# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Written by Jason Gabunilas

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_df = pd.read_csv('../WeatherPy/cities.csv')
cities_df

,Unnamed: 0,City Name,Latitude,Longitude,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
0,0,storforshei,66.40,14.52,55.40,54,75,9.17,NO,1594145702
1,1,avarua,-21.21,-159.78,71.60,78,74,10.29,CK,1594145682
2,2,chicama,-7.84,-79.15,72.10,57,40,11.70,PE,1594145705
3,3,la rioja,42.25,-2.50,86.00,25,0,5.82,ES,1594145706
4,4,sahuaripa,29.05,-109.23,94.89,34,73,4.36,MX,1594145710
...,...,...,...,...,...,...,...,...,...,...
553,553,flinders,-34.58,150.86,52.00,88,93,1.01,AU,1594146556
554,554,kidal,18.44,1.41,104.68,7,0,10.65,ML,1594146558
555,555,pathein,16.78,94.73,80.98,88,100,4.65,MM,1594146559
556,556,makakilo city,21.35,-158.09,80.60,65,1,5.82,US,1594146562
557,557,bagn,60.82,9.55,45.00,71,95,1.99,NO,1594146563

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps with API key
gmaps.configure(api_key = g_key)

In [4]:
# Store 'Latitude' and 'Longitude' into  locations, and store Humidity as the weight for the heatmap
locations = cities_df[["Latitude", "Longitude"]].astype(float)
humidity = cities_df["Humidity"].astype(float)
fig = gmaps.figure()

# When adding the heat layer, set the maximum intensity equal to the highest humidity in the dataframe
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(cities_df["Humidity"]),
                                 point_radius = 1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
ideal_weather = cities_df[(cities_df['Max Temp (F)'] < 80) & (cities_df['Max Temp (F)'] > 68) & (cities_df['Wind Speed'] < 8) & (cities_df['Cloudiness'] < 20) & (cities_df['Humidity'] < 50)]
ideal_weather.dropna(inplace = True)
del ideal_weather['Unnamed: 0']
ideal_weather

C:\Users\Jason\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,City Name,Latitude,Longitude,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
10,aksu,41.12,80.26,78.87,16,0,5.70,CN,1594145719
82,pittsburg,38.03,-121.88,79.00,38,1,3.36,US,1594145627
236,saint-denis,48.92,2.33,79.00,29,0,6.93,FR,1594146066
282,komsomolskiy,40.43,71.72,77.00,36,0,6.93,UZ,1594146137
369,laguna,38.42,-121.42,75.99,38,1,3.36,US,1594146275
433,san jose,37.34,-121.89,75.99,37,1,3.36,US,1594146348
443,ilebo,-4.32,20.58,78.48,35,3,0.92,CD,1594146387
528,pingliang,35.54,106.69,68.09,46,1,2.71,CN,1594146516
552,florence,43.77,11.25,78.80,39,11,4.70,IT,1594146416

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
# Add a hotel name column
ideal_weather["Hotel Name"] = ''
hotel_df = ideal_weather

C:\Users\Jason\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
# Set the initial, unchanging parameters
parameters = {
    "key" : g_key,
#     "query" : 'hotel',
    "type" : 'lodging',
    "radius" : '5000',
    }

# Set the base URL for the Google Place textsearch
base_url = 'https://maps.googleapis.com/maps/api/place/textsearch/json?'
    
# Loop over each city in the ideal_weather dataframe and extract the latitude and longitude from each city. Update the parameters dictionary with that location using the correct syntax from the API. Then make the request, JSON-ify the response, find the hotel name from the JSON object, and add the name of the first hotel in the result JSON to the hotel name column for that row in the dataframe
for index, row in hotel_df.iterrows():
    
    lat = row["Latitude"]
    lng = row["Longitude"]
    parameters["location"] = f'{lat},{lng}'
    hotel_info = requests.get(base_url, params=parameters)
    hotel_json = hotel_info.json()
#     print(json.dumps(hotel_json, indent = 4))
    hotel_name = hotel_json['results'][0]["name"]
#     print(hotel_name)
    hotel_df.loc[index, "Hotel Name"] = hotel_name

hotel_df

C:\Users\Jason\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,City Name,Latitude,Longitude,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
10,aksu,41.12,80.26,78.87,16,0,5.70,CN,1594145719,Pudong Holiday Hotel
82,pittsburg,38.03,-121.88,79.00,38,1,3.36,US,1594145627,Hampton Inn & Suites Pittsburg
236,saint-denis,48.92,2.33,79.00,29,0,6.93,FR,1594146066,Appart'City Paris Clichy Mairie - Appart HÃ´tel
282,komsomolskiy,40.43,71.72,77.00,36,0,6.93,UZ,1594146137,Ikathouse
369,laguna,38.42,-121.42,75.99,38,1,3.36,US,1594146275,Holiday Inn Express & Suites Elk Grove Central...
433,san jose,37.34,-121.89,75.99,37,1,3.36,US,1594146348,The Westin San Jose
443,ilebo,-4.32,20.58,78.48,35,3,0.92,CD,1594146387,HÃ´tel des palmes
528,pingliang,35.54,106.69,68.09,46,1,2.71,CN,1594146516,Xinxiang Hostel
552,florence,43.77,11.25,78.80,39,11,4.70,IT,1594146416,Italiana Hotels Florence

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City Name}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [9]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,
    info_box_content=hotel_info)
fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))